version: '3' 
services:
  frontend-ft:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend-ft
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env